[project]
name = "fhgr-tweather"
version = "0.1"
description = "Tweather App for SAD Module @FHGR"
dependencies = [
    "pandas",
    "pyproj",
    "openmeteo-requests"
]

[tool.setuptools]
py-modules = []

[tool.pyright]
include = ["."]
exclude = ["venv"]
venvPath = "."
venv = "venv"
