# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tweather

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 21 
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"
      - name: Install Python dependencies 
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install .
      - name: Install NPM dependencies 
        run: |
          cd frontend
          npm i
      - name: Lint Python Code 
        run: |
          cd backend
          ruff --output-format=github .
        continue-on-error: true
      - name: Lint Frontend Code 
        run: |
          cd frontend 
          npx eslint .
        continue-on-error: true 
      - name: Run Python Unit Tests
        run: |
          cd backend
          python -m unittest discover -v
        continue-on-error: false
